### ISSUE TITLE
Path or pattern "bower_components/loader.js/loader.js" did not match any files

### ISSUE THREAD

**Issue by kirantpatil** [benoithubert/sails-ember-carpooling#9]
Sir,

I modified the bower.js as below to make it install all the packages. What I did is simply took out the version number and replaced it with 'latest' then it installed the relevant package. Is this modification to bower.js correct ?

I started sails servers using 'sails lift' under project root directory.

When I run 'ember server' I get lot of DEPRECATION messages and at end you could see the Error message.

#### bower.js file is as below
{
    "name": "frontend-public",
    "dependencies": {
        "jquery": "latest",
        "ember": "latest",
        "ember-data": "1.0.0-beta.16",
        "ember-resolver": "~0.1.14",
        "loader.js": "ember-cli/loader.js#latest",
        "ember-cli-shims": "ember-cli/ember-cli-shims#latest",
        "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
        "ember-load-initializers": "ember-cli/ember-load-initializers#latest",
        "ember-qunit": "0.2.8",
        "ember-qunit-notifications": "0.0.7",
        "qunit": "~1.17.1",
        "uikit": "latest",
        "highlightjs": "latest",
        "moment": "latest",
        "validator-js": "latest",
        "emblem": "latest",
        "chance": "latest",
        "sprintf": "latest",
        "lodash": "latest",
        "ic-ajax": "latest"
  }
}

#### kpatil  ⋯  carpool  sails-ember-carpooling  frontend-public  ember server
version: 0.2.1

A new version of ember-cli is available (1.13.13). To install it, type ember update.
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Livereload server on port 35729
Serving on http://localhost:4200/
DEPRECATION: Using `{{view}}` or any path based on it (L1:C0) has been deprecated. [deprecation id: view.keyword.view] See http://emberjs.com/deprecations/v1.x#toc_view-and-controller-template-keywords for more details.
        at deprecatePath (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11431:32)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11399:7
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.Program (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18312:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at DeprecateViewAndControllerPaths_transform [as transform] (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11394:12)
        at Object.preprocess (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:17693:27)
        at compileSpec (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:12791:37)
DEPRECATION: The `bind-attr` helper (L13:C23) is deprecated in favor of HTMLBars-style bound attributes.
        at isBindAttrModifier (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11751:34)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11644:15
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
DEPRECATION: The `bind-attr` helper (L1:C7) is deprecated in favor of HTMLBars-style bound attributes.
        at isBindAttrModifier (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11751:34)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11644:15
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.Program (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18312:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at TransformBindAttrToAttributes_transform [as transform] (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11639:12)
        at Object.preprocess (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:17693:27)
        at compileSpec (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:12791:37)
DEPRECATION: Using `{{view}}` or any path based on it (L4:C12) has been deprecated. [deprecation id: view.keyword.view] See http://emberjs.com/deprecations/v1.x#toc_view-and-controller-template-keywords for more details.
        at deprecatePath (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11431:32)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11399:7
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
DEPRECATION: Using `{{view}}` or any path based on it (L15:C8) has been deprecated. [deprecation id: view.keyword.view] See http://emberjs.com/deprecations/v1.x#toc_view-and-controller-template-keywords for more details.
        at deprecatePath (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11431:32)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11399:7
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
DEPRECATION: Using the '{{#each item in model}}' form of the {{#each}} helper (L5:C12) is deprecated. Please use the block param form instead ('{{#each model as |item|}}'). See http://emberjs.com/guides/deprecations/#toc_code-in-code-syntax-for-code-each-code for more details.
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11938:36
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
DEPRECATION: Using `{{view}}` or any path based on it (L24:C8) has been deprecated. [deprecation id: view.keyword.view] See http://emberjs.com/deprecations/v1.x#toc_view-and-controller-template-keywords for more details.
        at deprecatePath (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11431:32)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11399:7
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
DEPRECATION: Using the `{{view "string"}}` helper is deprecated. (L24:C8)  [deprecation id: view.helper] See http://emberjs.com/deprecations/v1.x#toc_ember-view for more details.
        at deprecateHelper (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11491:34)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11477:7
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
DEPRECATION: The `bind-attr` helper (L1:C5) is deprecated in favor of HTMLBars-style bound attributes.
        at isBindAttrModifier (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11751:34)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11644:15
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.Program (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18312:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at TransformBindAttrToAttributes_transform [as transform] (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11639:12)
        at Object.preprocess (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:17693:27)
        at compileSpec (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:12791:37)
DEPRECATION: Using `{{view}}` or any path based on it (L2:C0) has been deprecated. [deprecation id: view.keyword.view] See http://emberjs.com/deprecations/v1.x#toc_view-and-controller-template-keywords for more details.
        at deprecatePath (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11431:32)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11399:7
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.Program (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18312:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at DeprecateViewAndControllerPaths_transform [as transform] (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11394:12)
        at Object.preprocess (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:17693:27)
        at compileSpec (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:12791:37)
DEPRECATION: Using the `{{view "string"}}` helper is deprecated. (L2:C0)  [deprecation id: view.helper] See http://emberjs.com/deprecations/v1.x#toc_ember-view for more details.
        at deprecateHelper (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11491:34)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11477:7
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.Program (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18312:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at DeprecateViewHelper_transform [as transform] (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11472:12)
        at Object.preprocess (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:17693:27)
        at compileSpec (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:12791:37)
DEPRECATION: Using `{{view}}` or any path based on it (L7:C12) has been deprecated. [deprecation id: view.keyword.view] See http://emberjs.com/deprecations/v1.x#toc_view-and-controller-template-keywords for more details.
        at deprecatePath (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11431:32)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11399:7
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
DEPRECATION: Using the '{{#each item in model}}' form of the {{#each}} helper (L2:C0) is deprecated. Please use the block param form instead ('{{#each model as |item|}}'). See http://emberjs.com/guides/deprecations/#toc_code-in-code-syntax-for-code-each-code for more details.
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11938:36
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at visitors.Program (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18312:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at TransformEachInToBlockParams_transform [as transform] (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11917:12)
DEPRECATION: The `bind-attr` helper (L3:C53) is deprecated in favor of HTMLBars-style bound attributes.
        at isBindAttrModifier (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11751:34)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11644:15
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at visitors.Program (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18312:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
DEPRECATION: The `bind-attr` helper (L5:C17) is deprecated in favor of HTMLBars-style bound attributes.
        at isBindAttrModifier (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11751:34)
        at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11644:15
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18302:7)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
        at visitors.ElementNode (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18318:16)
        at Walker.children (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18335:7)
        at Walker.visit (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:18303:12)
DEPRECATION: Using `{{view}}` or any path based on it (L2:C33) has been deprecated. [deprecation id: view.keyword.view] See http://emberjs.com/deprecations/v1.x#toc_view-and-controller-template-keywords for more details.
        at deprecatePath (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/bower_components/ember/ember-template-compiler.js:11431:32)
...
...
...
Path or pattern "bower_components/loader.js/loader.js" did not match any files
Error: Path or pattern "bower_components/loader.js/loader.js" did not match any files
    at Object.multiGlob (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/home/kpatil/Documents/carpool/sails-ember-carpooling/frontend-public/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)

Thanks.

**Comment by benoithubert** [comment]
Sorry for the late reply. I am more busy than ever and really can't spend time on the project now.
It seems that you solved the Bower issue. The issues you have now are related to deprecations indeed.
I did most of the work on this project quite a few months ago.
Since then Ember has evolved a lot. They removed Ember.View in favor of Ember.Component. All they do is with a good reason. However I haven't had enough time to make the project evolve at the same pace as Ember did.
That is why you see so many deprecations. I hope in the future i can fix them but right now I can't, sorry for that!
Thanks for being so patient. Regards,

Benoît

**Comment by kirantpatil** [comment]
I am happy that in spite of your busy schedule you are replying. We will start working on this issue and try to resolve it. If we struck anywhere will get back to you for further assistance.

Thanks.

**Comment by stefanpenner** [comment]
> ember server
> version: 0.2.1

ember cli 0.2.1 is quite old, let me recommend upgrade to something more recent. 1.13.13 is the latest release.

**Comment by kirantpatil** [comment]
@stefanpenner, thanks and upgrade to 1.13.13 resolved the issue.
